id: PYSEC-0000-CVE-2011-4138
package:
  name: django
  ecosystem: PyPI
details: The verify_exists functionality in the URLField implementation in Django
  before 1.2.7 and 1.3.x before 1.3.1 originally tests a URL's validity through a
  HEAD request, but then uses a GET request for the new target URL in the case of
  a redirect, which might allow remote attackers to trigger arbitrary GET requests
  with an unintended source IP address via a crafted Location header.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 1.2.7
  - type: ECOSYSTEM
    introduced: '1.3'
    fixed: 1.3.1
references:
- type: WEB
  url: https://www.djangoproject.com/weblog/2011/sep/10/127/
- type: WEB
  url: http://openwall.com/lists/oss-security/2011/09/13/2
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=737366
- type: WEB
  url: http://openwall.com/lists/oss-security/2011/09/11/1
- type: WEB
  url: https://www.djangoproject.com/weblog/2011/sep/09/
- type: WEB
  url: http://secunia.com/advisories/46614
- type: WEB
  url: http://www.debian.org/security/2011/dsa-2332
- type: WEB
  url: https://hermes.opensuse.org/messages/14700881
aliases:
- CVE-2011-4138
modified: "2018-01-18T02:29:00Z"
published: "2011-10-19T10:55:00Z"
