id: PYSEC-2020-92
package:
  name: py
  ecosystem: PyPI
summary: Vulnerability in py
details: A denial of service via regular expression in the py.path.svnwc component
  of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time
  denial of service attack by supplying malicious input to the blame functionality.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 1.10.0
references:
- type: WEB
  url: https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144
- type: WEB
  url: https://github.com/pytest-dev/py/issues/256
- type: WEB
  url: https://github.com/pytest-dev/py/pull/257
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AYWNYEV3FGDHPIHX4DDUDMFZ6NLCQRC4/
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CHDTINIBJZ67T3W74QTBIY5LPKAXEOGR/
aliases:
- CVE-2020-29651
modified: "2021-01-05T03:15:00Z"
published: "2020-12-09T07:15:00Z"
